apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: s3proxy
  labels:
    app: s3proxy
spec:
  storageClassName: nfs-volumes
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi